###
POST http://localhost:8080/login HTTP/1.1
Content-Type: application/json

{
    "email": "donatao@gmail.com",
    "password": "123"
}
###

###
POST http://localhost:8080/signin HTTP/1.1
Content-Type: application/json

{
    "email": "donatao@gmail.com",
    "password": "123",
    "first_name": "Lucca",
    "last_name": "Donatao",
    "document": "11111111111",
    "address": "Vila Branca",
    "city": "Jacareí",
    "state": "SP",
    "zip_code": "11111111",
    "phone_ddd": "12",
    "phone_number": "111111111",
    "creation_date": "NOW()"
}
###

###
POST http://localhost:8080/productgroup HTTP/1.1
Content-Type: application/json

{
    "product_type": "Graphics Card",
    "creation_date": "NOW()"
}
###

###
POST http://localhost:8080/productgroupupdate HTTP/1.1
Content-Type: application/json

{
    "group_id": "3",
    "product_type": "Ram",
    "update_date": "NOW()"
}
###

###
POST http://localhost:8080/productgroupdelete HTTP/1.1
Content-Type: application/json

{
    "group_id": "22",
    "delete_date": "NOW()",
    "update_date": "NOW()"
}
###

###
POST http://localhost:8080/product HTTP/1.1
Content-Type: application/json

{
    "group_id": "3",
    "label": "Kingston",
    "product_name": "Fury Beast - 16GB - DDR4",
    "product_quantity": "5",
    "product_price": "849,90",
    "creation_date": "NOW()"
}
###

###
POST http://localhost:8080/productupdate HTTP/1.1
Content-Type: application/json

{
    "product_id": "6",
    "group_id": "21",
    "update_date": "NOW()"
}
###

###
POST http://localhost:8080/productdelete HTTP/1.1
Content-Type: application/json

{
    "product_id": "4",
    "delete_date": "NOW()",
    "update_date": "NOW()"
}
###